### ISSUE TITLE
에디터 수정 사항 반영

### ISSUE THREAD

**Issue by JewonYeon** [memory-makers/rolling-paper#106]
### ISSUE
- type : fix

### TODO
- [x] 폰트 선택 옵션에 해당 서체 반영
- [x] 에디터 옵션 height px 고정
- [x] 폰트 색상 옵션 변경

### 기타
-
