### ISSUE TITLE
기타 수정사항

### ISSUE THREAD

**Issue by zellytozelly** [memory-makers/rolling-paper#115]
### ISSUE
- type : feat

### TODO
- [ ] 닉네임 API 타입 지정 
- [ ] 닉네임 없을 때 [클릭해서 닉네임 설정] 삭제
- [ ] 무한 요청 방지
