### ISSUE TITLE
feat : 마이페이지 UI 전면 수정

### ISSUE THREAD

**Issue by kyhyun** [memory-makers/rolling-paper#116]
### ISSUE
- type : feat

### TODO
- [x] 구현해야할 것
  - [x] 마이 페이지 전체 레이아웃 컴포넌트 수정
  - [x] 페이퍼 내 리스트 아이템 컴포넌트 수정
  - [x] 상태를 표시하기 위한 컴포넌트 추가

### 기타
- 내부 드롭다운은 우선 기존에 있던 것과 조합해 본 후에 변경할지 정해야할 것 같습니다.
