### ISSUE TITLE
사파리, 모바일 체크

### ISSUE THREAD

**Issue by YumYumNyang** [memory-makers/rolling-paper#117]
### ISSUE
- type : bug

### TODO
- 해결
- [x] 모바일 height 100vh 이슈 - 아래 바에 가려짐
- [x] 사파리 aspect ratio 이슈
- [x] 사파리 로고 애니메이션 이슈
