### ISSUE TITLE
배포 전 QA 사항 수정 - 롤링페이퍼 페이지

### ISSUE THREAD

**Issue by YumYumNyang** [memory-makers/rolling-paper#131]
### ISSUE
- type : bug

### TODO
- [x] 카드 자세히 보기 - 카드 길어졌을 때 스크롤 문제
- [x] 롤링페이퍼 페이지에서 홈 버튼 추가하기 (추가사항) 
- [x] 첫 랜더링 시점 줌 인
- [x] 스티커 생성 위치 변경
- [x] 카드 텍스트 모든 글자 break 하기
