### ISSUE TITLE
QA 수정사항

### ISSUE THREAD

**Issue by zellytozelly** [memory-makers/rolling-paper#132]
### ISSUE
- type : fix

### TODO
- [ ] [모달 생성] 달력에 입력 막기 / moment.js
- [x] CSS 모달 커서 처리 / 테마 pointer
- [x] GA
- [ ] 이미지로 저장하기 버튼 색 반전시키고 순서 바꾸기 / 시안 올려볼게요 ABC
- [ ] sending 광고 위치 제안

### 기타
- 논의 사항이나, 고려해야 할 점을 작성해주세요.
