### ISSUE TITLE
QA 수정사항

### ISSUE THREAD

**Issue by JewonYeon** [memory-makers/rolling-paper#133]
### ISSUE
- type : chore

### TODO
- [x] 카드 생성 시 유효성 검사 (카드 미작성 시 작성 권유 모달 팝업)
- [x] 카드 글자수 제한 (200자)
- [x] 에디터 옵션 체크표시 수정
- [x] 날짜 달력 선택만 가능하도록 수정 (타이핑 X)

### 기타
- 논의 사항이나, 고려해야 할 점을 작성해주세요.
