### ISSUE TITLE
마이페이지 스타일 수정

### ISSUE THREAD

**Issue by kyhyun** [memory-makers/rolling-paper#141]
### ISSUE
- type : style

### TODO
- [x] 페이지 드롭다운 버튼 영역 넓히기
- [x] 전체 레이아웃의 높이 조정 (테두리 짤림 문제 수정)
- [x] 마이페이지 컨테이너 상단 패딩 조정
- [x] 페이지 내 전체 폰트 사이즈, 컨텐츠의 크기, 높이 조정
- [x] 리스트의 드롭다운 버튼 조작 시, 리스트 전체에 색깔이 들어오는 문제 수정 (hover 제거) 
- [x] 플로팅 메세지 제거 (모달 대체)
