### ISSUE TITLE
모달 axios 연결

### ISSUE THREAD

**Issue by zellytozelly** [memory-makers/rolling-paper#46]
### ISSUE
- type : feat

### TODO
- [x] 구현해야할 것
  - [x] (components/layout/Header.tsx)
    - [x] 모달 axios 연결 (닉네임 추가) 
    - [x] 모달 axios 연결 (닉네임 수정) 

  - [x] (pages/MyPage/index.tsx)
    - [x] 모달 axios 연결 (롤링페이퍼 추가1)
    - [x] 모달 axios 연결 (롤링페이퍼 추가2)

  - [x] (pages/MyPage/MyPageItem/MyPageDropdown/index.tsx)
    - [x] 모달 axios 연결 (롤링페이퍼 수정) 
    - [x] 모달 axios 연결 (롤링페이퍼 삭제)
    - [x] 모달 axios 연결 (호스트 링크공유)
    - [x] 드롭다운에 `수정하기` 추가 

### 기타
- 논의 사항이나, 고려해야 할 점을 작성해주세요.
