### ISSUE TITLE
마이페이지 데이터 fetch 작업

### ISSUE THREAD

**Issue by kyhyun** [memory-makers/rolling-paper#49]
[이슈 작성 시 이 줄은 지워주세요! `Assignee` : 본인 선택 필수!)
### ISSUE
- type : feat

### TODO
- [x] 구현해야할 것
  - [x] 마이페이지 데이터 연결 작업
  - [x] 로그인한 유저 정보에 따른 Roll 데이터 렌더링
- [x] 해결해야할 것
  - [x] 더미 데이터 제거

**Comment by kyhyun** [comment]
레몬과 공동작업으로 49번 이슈는 해결되어 Close 하겠습니다.
