### ISSUE TITLE
롤링페이퍼 작성 기능 구현

### ISSUE THREAD

**Issue by JewonYeon** [memory-makers/rolling-paper#50]
### ISSUE
- type : feat

### TODO
- [x] 보내는 사람 이름 설정 : 미 입력 시 익명
- [x] 타이핑
- [x] 꾸밈 요소 (배경색, 폰트, 글자색) -> focus 에 따라 on / off
- [ ] 완료 버튼
  - [ ] 작성 완료 api 요청 

### 기타
-
