### ISSUE TITLE
마이페이지 드롭다운 기능 수정

### ISSUE THREAD

**Issue by kyhyun** [memory-makers/rolling-paper#56]
### ISSUE
- type : refactor

### TODO
- [x] 해결해야할 것
  - [x] 드롭다운 리스트의 나만보기 및 전체보기 토글과 svg 아이콘 기능 분리
  - [x] 의미에 맞는 변수 네이밍으로 변경
  - [x] 롤링페이퍼(Roll) 간에 드롭다운 겹침 문제 해결

### 기타
- 나만보기와 전체보기의 조작은 드롭다운 리스트 안의 토글을 통해서만 조작할 수 있도록 하고 롤링페이퍼 안의 UI 아이콘은 가시적인 요소로만 활용될 수 있도록 해서 기능을 분리하고자 합니다.
