### ISSUE TITLE
모달관련 작업

### ISSUE THREAD

**Issue by zellytozelly** [memory-makers/rolling-paper#67]
### ISSUE
- type : feat

### TODO
A.
- [ ] sending에 URL 붙이기
- [ ] 로그아웃 카카오쪽 처리 구현 필요
- [ ] 로그아웃 디자인 컨펌 후 수정
- [ ] rollingpaper/:id에 이상한 값이 들어가 500에러가 난 경우 처리

B.
- [ ] 빈 값 입력시 비어있다고 문구 띄어주기
- [ ] 복사버튼 클릭시 복사되었다고 알려주기
- [ ] 닉네임 에러바운더리
- [ ] 마이페이지 캡슐 에러바운더리

### 기타
- 닉네임 길어질 경우 말줄임표 처리 문의
- 카드 최종 확인 모달 데이터 넘김 처리 협의
