### ISSUE TITLE
오픈 날짜 처리, 에러 처리

### ISSUE THREAD

**Issue by YumYumNyang** [memory-makers/rolling-paper#69]
### ISSUE
- type : feat

### TODO
- [ ] 오픈날짜 이후, 카드 생성 및 스티커 수정불가
- [ ] 오픈날짜까지 남은 시간 보여주기
- [ ] layout min-height 설정
- [ ] id가 없으면 에러 처리 해주기
