### ISSUE TITLE
마이페이지 기능 수정 및 제거

### ISSUE THREAD

**Issue by kyhyun** [memory-makers/rolling-paper#70]
### ISSUE
- type : fix

### TODO
- [ ] 구현해야할 것
  - [ ] 롤링페이퍼 이름 길이에 대한 폰트 배치 변경 ( 1 줄 + 말 줄임표 -> 2줄 )
- [ ] 해결해야할 것
  - [ ]  나만 보기, 모두 보기 기능 및 스타일 제거
  - [ ] 로그아웃 쿠키 삭제 처리

### 기타
- 나만 보기, 모두 보기는 기능에 대한 사용성을 고려해봤을 때 특정 사용자에게만 보이게 하는 기능에 대한 필요성이 의문이 나왔고 
9월 29일자 회의를 통해서 해당 기능의 필요성이 없다고 판단하여 제거하게 됐습니다.
- 오픈일자에 따라 롤링페이퍼에 글을 읽기 전용의 상태로 만들어야 하기 때문에 상세 롤링페이퍼에서 
오픈 날짜에 대한 처리를 하도록 이야기가 진행됐습니다.
