### ISSUE TITLE
레이아웃 디테일 추가 작업

### ISSUE THREAD

**Issue by zellytozelly** [memory-makers/rolling-paper#91]
### ISSUE
- type : feat

### TODO
- [x] 복사되었습니다 팝업메시지
- [x] sending 돌아가기 화살표 아이콘 변경 + 텍스트 추가
- [x] header 데이터 세션스토리지 관리 -> sending 새로고침시 남아있음.
- [x] sending 버튼 색 차이 주기 (for UX)
- [x] mypage 톤 조정 `$textGray: #868686;` -> `$textGray: #a4a4a4;`
- [x] 공유 모달 리팩토링, 3개 하나로 합치기 + svg import
  - **파일변동**
  - 레몬 `CreateRoll` / CreateShareRoll(최초생성) -> ShareRollItem
  - 기린 `MyPageDropdown` / ChangeShareRoll(드롭다운) -> ShareRoll
  - 얌얌 `components/rollingpaper/Buttons.tsx` / WriterShareRoll(작성자쪽) -> ShareRoll

- [x] 공유 모달 url 없을 경우, 버튼 클릭 방지 처리
