### ISSUE TITLE
반응형 조절

### ISSUE THREAD

**Issue by zellytozelly** [memory-makers/rolling-paper#93]
### ISSUE
- type : feat

### TODO
- [x] sending 모바일 height 반응형
- [x] 403 error page
- [x] 오늘날짜 클릭 막기
- [x] 롤링페이퍼 타이틀 빈값 → 빨강색 에러메시지
- [x] 클립보드 클릭시 아이콘 색 변하도록
- [x] input 클릭했을 때 외곽선 삭제

### 기타
- 논의 사항이나, 고려해야 할 점을 작성해주세요.
